// Code generated by coz. DO NOT EDIT.
/**
 * Base of the-resource
 * @module the-resource-base
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get DataTypes () { return _d(require('./DataTypes')) },
  get TheResource () { return _d(require('./TheResource')) },
  get create () { return _d(require('./create')) },
  get isResourceClass () { return _d(require('./isResourceClass')) },
  get mixins () { return _d(require('./mixins')) },
  get default () { return _d(require('./create')) },
}
