// Code generated by coz. DO NOT EDIT.
/**
 * Base of the-resource
 * @module the-resource-base
 */
'use strict'

import DataTypes from './DataTypes'
import TheResource from './TheResource'
import create from './create'
import isResourceClass from './isResourceClass'
import mixins from './mixins'

export {
  DataTypes,
  TheResource,
  create,
  isResourceClass,
  mixins,
}

export default create
