// Code generated by coz. DO NOT EDIT.
/**
 * Mixins
 * @module mixins
 */
'use strict'

const _d = (m) => 'default' in m ? m.default : m

module.exports = {
  get listenMix () { return _d(require('./listenMix')) },
  get writeOnceMix () { return _d(require('./writeOnceMix')) },
}
